image: node:alpine

stages:
  - init
  - deploy

init:
  stage: init
  script:
    - npm cache clean
    - rm -rf node-modules
    - npm install

deploy_production:
  stage: deploy
  script:
    - git remote add https://gitlab.com/Mortiferr/perswayable-bot.git
    - git push master
    - echo "Deployed to production server"
  environment:
  name: production
  when: manual
  only:
    - master